function validate_solar_data(location)
    % VALIDATE_SOLAR_DATA - Comprehensive validation of preprocessed solar dataset
    %
    % DESCRIPTION:
    %   Performs strict physical and structural validations on the CSV file
    %   generated by prepare_solar_data.m. Checks for data integrity, missing
    %   values, physical consistency, and nighttime-irradiance anomalies.
    %
    % USAGE:
    %   validate_solar_data()              % Default: ISTANBUL
    %   validate_solar_data('ISTANBUL')
    %   validate_solar_data('ANKARA')
    %
    % VALIDATION CHECKS:
    %   1. Structural    : 12 months × 86401 rows per month
    %   2. Missing Data  : No NaN, Inf, or empty values
    %   3. Nighttime     : Sun_Elevation < 0 ⟹ Irradiance = 0
    %   4. Zenith        : Sun_Elevation ≤ 90°
    %   5. Visual        : Dual-axis plot (GHI vs. Sun_Elevation) for June
    %
    % AUTHOR: Data Validation Pipeline
    % DATE: 2026-03-06
    % ═══════════════════════════════════════════════════════════════════════════

    %% DEFAULTS
    if nargin < 1 || isempty(location)
        location = 'ANTALYA';  % Default location for validation
    end

    %% RESOLVE FILE PATH
    script_dir   = fileparts(mfilename('fullpath'));
    csv_filename = sprintf('%s_Data.csv', upper(location));
    csv_filepath = fullfile(script_dir, csv_filename);

    %% BANNER
    fprintf('\n╔════════════════════════════════════════════════════════════════╗\n');
    fprintf('║  SOLAR DATA VALIDATION PIPELINE                               ║\n');
    fprintf('║  Structural, Physical & Consistency Checks                    ║\n');
    fprintf('╚════════════════════════════════════════════════════════════════╝\n\n');
    
    fprintf('  Location  : %s\n', upper(location));
    fprintf('  File      : %s\n', csv_filename);
    fprintf('  Path      : %s\n\n', csv_filepath);

    %% LOAD FILE
    if ~isfile(csv_filepath)
        fprintf('  ERROR : File not found!\n');
        fprintf('         Expected: %s\n\n', csv_filepath);
        return;
    end

    try
        data = readtable(csv_filepath);
    catch ME
        fprintf('  ERROR : Failed to read CSV file.\n');
        fprintf('         %s\n\n', ME.message);
        return;
    end

    %% INITIALIZE PASS/FAIL COUNTERS
    checks_passed = 0;
    checks_total  = 0;

    %% ═════════════════════════════════════════════════════════════════════
    %  CHECK 1: STRUCTURAL INTEGRITY
    %% ═════════════════════════════════════════════════════════════════════
    checks_total = checks_total + 1;
    fprintf('┌─ CHECK 1: STRUCTURAL INTEGRITY ─────────────────────────────┐\n');

    % Expected: 12 months × 86401 rows
    expected_rows = 12 * 86401;
    actual_rows   = height(data);
    unique_months = numel(unique(data.Month));

    struct_pass = (actual_rows == expected_rows) && (unique_months == 12);

    if struct_pass
        fprintf('│ ✓ PASS\n');
        fprintf('│   Months       : %d (expected 12)\n', unique_months);
        fprintf('│   Total rows   : %d (expected %d = 12 × 86401)\n', actual_rows, expected_rows);
        checks_passed = checks_passed + 1;
    else
        fprintf('│ ✗ FAIL\n');
        fprintf('│   Months       : %d (expected 12)\n', unique_months);
        fprintf('│   Total rows   : %d (expected %d = 12 × 86401)\n', actual_rows, expected_rows);
    end

    % Check each month has exactly 86401 rows
    fprintf('│\n│   Per-month breakdown:\n');
    for m = 1:12
        month_rows = sum(data.Month == m);
        status = '✓';
        if month_rows ~= 86401
            status = '✗';
        end
        fprintf('│   [%s] Month %2d : %d rows\n', status, m, month_rows);
    end

    fprintf('└────────────────────────────────────────────────────────────┘\n\n');

    %% ═════════════════════════════════════════════════════════════════════
    %  CHECK 2: MISSING DATA (NaN, Inf)
    %% ═════════════════════════════════════════════════════════════════════
    checks_total = checks_total + 1;
    fprintf('┌─ CHECK 2: MISSING DATA & ANOMALIES ──────────────────────────┐\n');

    col_names = {'Month', 'Time_in_Seconds', 'GHI', 'Beam', 'DHI', ...
                 'Sun_Elevation', 'Sun_Azimuth'};
    
    all_clean = true;
    issue_count = 0;

    for c = 1:numel(col_names)
        col_name = col_names{c};
        col_data = data.(col_name);
        
        nan_count = sum(isnan(col_data));
        inf_count = sum(isinf(col_data));
        
        if nan_count > 0 || inf_count > 0
            all_clean = false;
            fprintf('│ [%s] %s\n', '✗', col_name);
            fprintf('│      NaN: %d,  Inf: %d\n', nan_count, inf_count);
            issue_count = issue_count + nan_count + inf_count;
        else
            fprintf('│ [✓] %s  (clean)\n', col_name);
        end
    end

    if all_clean
        fprintf('│\n│ ✓ PASS - No missing or anomalous values detected\n');
        checks_passed = checks_passed + 1;
    else
        fprintf('│\n│ ✗ FAIL - Found %d anomalous values\n', issue_count);
    end

    fprintf('└────────────────────────────────────────────────────────────┘\n\n');

    %% ═════════════════════════════════════════════════════════════════════
    %  CHECK 3: NIGHTTIME PHYSICS (Sun below horizon ⟹ Irradiance = 0)
    %% ═════════════════════════════════════════════════════════════════════
    checks_total = checks_total + 1;
    fprintf('┌─ CHECK 3: NIGHTTIME PHYSICS CONSISTENCY ─────────────────────┐\n');

    nighttime_mask  = data.Sun_Elevation < 0;                      % Sun is below horizon
    total_irrad     = data.GHI + data.Beam + data.DHI;          % Total irradiance (full array)
    % Use tolerance (1e-4 W/m2) to account for floating-point artifacts from pchip interpolation
    bad_night_mask  = nighttime_mask & (total_irrad > 1e-4);    % Anomaly: irradiance at night
    bad_nighttime   = sum(bad_night_mask);

    if bad_nighttime == 0
        fprintf('│ ✓ PASS\n');
        fprintf('│   Nighttime rows (Sun_Elevation < 0) : %d\n', sum(nighttime_mask));
        fprintf('│   Rows with irradiance at night     : %d\n', bad_nighttime);
        checks_passed = checks_passed + 1;
    else
        fprintf('│ ✗ FAIL\n');
        fprintf('│   Nighttime rows (Sun_Elevation < 0) : %d\n', sum(nighttime_mask));
        fprintf('│   ✗ Rows with irradiance at night     : %d  [ANOMALY!]\n', bad_nighttime);
        
        % Show examples of anomalies
        bad_idx = find(bad_night_mask);
        if ~isempty(bad_idx)
            fprintf('│\n│   Examples of anomalies (first 5):\n');
            for i = 1:min(5, numel(bad_idx))
                idx = bad_idx(i);
                fprintf('│   Row %d: Month=%d, Time=%ds, Elev=%.1f°, GHI=%.1f, Beam=%.1f, DHI=%.1f\n', ...
                        idx, data.Month(idx), data.Time_in_Seconds(idx), data.Sun_Elevation(idx), ...
                        data.GHI(idx), data.Beam(idx), data.DHI(idx));
            end
        end
    end

    fprintf('└────────────────────────────────────────────────────────────┘\n\n');

    %% ═════════════════════════════════════════════════════════════════════
    %  CHECK 4: ZENITH SANITY (Sun elevation ≤ 90°)
    %% ═════════════════════════════════════════════════════════════════════
    checks_total = checks_total + 1;
    fprintf('┌─ CHECK 4: ZENITH SANITY CHECK ───────────────────────────────┐\n');

    max_elev = max(data.Sun_Elevation);
    bad_zenith = sum(data.Sun_Elevation > 90);

    if bad_zenith == 0 && max_elev <= 90
        fprintf('│ ✓ PASS\n');
        fprintf('│   Sun Elevation range : [%.2f°, %.2f°]\n', ...
                min(data.Sun_Elevation), max_elev);
        fprintf('│   Max elevation       : %.2f° (valid, ≤ 90°)\n', max_elev);
        checks_passed = checks_passed + 1;
    else
        fprintf('│ ✗ FAIL\n');
        fprintf('│   Sun Elevation range : [%.2f°, %.2f°]\n', ...
                min(data.Sun_Elevation), max_elev);
        fprintf('│   ✗ Invalid values    : %d rows exceed 90°\n', bad_zenith);
    end

    fprintf('└────────────────────────────────────────────────────────────┘\n\n');

    %% ═════════════════════════════════════════════════════════════════════
    %  SUMMARY REPORT
    %% ═════════════════════════════════════════════════════════════════════
    fprintf('╔════════════════════════════════════════════════════════════════╗\n');
    fprintf('║  VALIDATION SUMMARY                                          ║\n');
    fprintf('╚════════════════════════════════════════════════════════════════╝\n\n');

    fprintf('  Checks Passed : %d / %d\n', checks_passed, checks_total);

    if checks_passed == checks_total
        fprintf('  Status        : ✓ ALL VALIDATIONS PASSED\n\n');
    else
        fprintf('  Status        : ✗ SOME VALIDATIONS FAILED\n\n');
        return;  % Exit early if validation fails
    end

    %% ═════════════════════════════════════════════════════════════════════
    %  SANITY PLOT: GHI vs Sun_Elevation for June (Month 6)
    %% ═════════════════════════════════════════════════════════════════════
    fprintf('  Generating sanity plot for June (Month 6)...\n\n');

    june_idx = data.Month == 6;
    june_data = data(june_idx, :);

    fig = figure('Name', sprintf('Solar Data Sanity Check - %s (June)', upper(location)), ...
                 'NumberTitle', 'off', 'Position', [100 100 1200 600]);

    % Create dual-axis plot
    yyaxis left
    plot(june_data.Time_in_Seconds / 3600, june_data.GHI, 'LineWidth', 2.5, 'Color', [1, 0.7, 0]);
    ylabel('Global Horizontal Irradiance (GHI) [W/m²]', 'FontSize', 12, 'FontWeight', 'bold');
    ylim([0, max(june_data.GHI) * 1.1]);
    grid on;
    ax_left = gca;
    ax_left.YColor = [1, 0.7, 0];

    yyaxis right
    plot(june_data.Time_in_Seconds / 3600, june_data.Sun_Elevation, 'LineWidth', 2.5, 'Color', [0, 0.4, 1]);
    ylabel('Sun Elevation Angle [°]', 'FontSize', 12, 'FontWeight', 'bold');
    ax_right = gca;
    ax_right.YColor = [0, 0.4, 1];

    xlabel('Time [hours]', 'FontSize', 12, 'FontWeight', 'bold');
    title(sprintf('Irradiance vs Sun Position - %s (June, Klein Rep. Day)', upper(location)), ...
          'FontSize', 14, 'FontWeight', 'bold');
    
    % Legend
    legend('GHI [W/m²]', 'Sun Elevation [°]', 'Location', 'best', 'FontSize', 11);

    grid on;

    % Additional statistics
    fprintf('╔════════════════════════════════════════════════════════════════╗\n');
    fprintf('║  JUNE STATISTICS                                             ║\n');
    fprintf('╚════════════════════════════════════════════════════════════════╝\n\n');
    fprintf('  GHI       : Min=%.1f,  Max=%.1f,  Mean=%.1f [W/m²]\n', ...
            min(june_data.GHI), max(june_data.GHI), mean(june_data.GHI));
    fprintf('  Beam      : Min=%.1f,  Max=%.1f,  Mean=%.1f [W/m²]\n', ...
            min(june_data.Beam), max(june_data.Beam), mean(june_data.Beam));
    fprintf('  DHI       : Min=%.1f,  Max=%.1f,  Mean=%.1f [W/m²]\n', ...
            min(june_data.DHI), max(june_data.DHI), mean(june_data.DHI));
    fprintf('  Elevation : Min=%.1f,  Max=%.1f,  Mean=%.1f [°]\n', ...
            min(june_data.Sun_Elevation), max(june_data.Sun_Elevation), mean(june_data.Sun_Elevation));
    fprintf('  Azimuth   : Min=%.1f,  Max=%.1f [°]\n\n', ...
            min(june_data.Sun_Azimuth), max(june_data.Sun_Azimuth));

    fprintf('✓ Validation complete! Dataset is ready for simulation.\n\n');

end
